<?php
namespace Water\Vular\Elements\Vular;

use Water\Vular\Elements\Vuetify\VCombobox;

final class VularCountry extends VCombobox{

    public function __construct(){
        parent::__construct();
        //$this->defaultValue([]);
        //$this->itemValue('id');
        //$this->itemText('name');
        $this->items([
            __('Afghanistan'),
            __('Aland Islands'),
            __('Albania'),
            __('Algeria'),
            __('American Samoa'),
            __('Andorra'),
            __('Angola'),
            __('Anguilla'),
            __('Antarctica'),
            __('Antigua And Barbuda'),
            __('Argentina'),
            __('Armenia'),
            __('Aruba'),
            __('Australia'),
            __('Austria'),
            __('Azerbaijan'),
            __('Bahamas'),
            __('Bahrain'),
            __('Bangladesh'),
            __('Barbados'),
            __('Belarus'),
            __('Belgium'),
            __('Belize'),
            __('Benin'),
            __('Bermuda'),
            __('Bhutan'),
            __('Bolivia'),
            __('Bosnia And Herzegovina'),
            __('Botswana'),
            __('Bouvet Island'),
            __('Brazil'),
            __('British Indian Ocean Territory'),
            __('Brunei Darussalam'),
            __('Bulgaria'),
            __('Burkina Faso'),
            __('Burundi'),
            __('Cambodia'),
            __('Cameroon'),
            __('Canada'),
            __('Cape Verde'),
            __('Cayman Islands'),
            __('Central African Republic'),
            __('Chad'),
            __('Chile'),
            __('China'),
            __('Christmas Island'),
            __('Cocos (Keeling) Islands'),
            __('Colombia'),
            __('Comoros'),
            __('Congo'),
            __('Congo, Democratic Republic'),
            __('Cook Islands'),
            __('Costa Rica'),
            __('Cote D\'Ivoire'),
            __('Croatia'),
            __('Cuba'),
            __('Cyprus'),
            __('Czech Republic'),
            __('Denmark'),
            __('Djibouti'),
            __('Dominica'),
            __('Dominican Republic'),
            __('Ecuador'),
            __('Egypt'),
            __('El Salvador'),
            __('Equatorial Guinea'),
            __('Eritrea'),
            __('Estonia'),
            __('Ethiopia'),
            __('Falkland Islands (Malvinas)'),
            __('Faroe Islands'),
            __('Fiji'),
            __('Finland'),
            __('France'),
            __('French Guiana'),
            __('French Polynesia'),
            __('French Southern Territories'),
            __('Gabon'),
            __('Gambia'),
            __('Georgia'),
            __('Germany'),
            __('Ghana'),
            __('Gibraltar'),
            __('Greece'),
            __('Greenland'),
            __('Grenada'),
            __('Guadeloupe'),
            __('Guam'),
            __('Guatemala'),
            __('Guernsey'),
            __('Guinea'),
            __('Guinea-Bissau'),
            __('Guyana'),
            __('Haiti'),
            __('Heard Island & Mcdonald Islands'),
            __('Holy See (Vatican City State)'),
            __('Honduras'),
            __('Hong Kong'),
            __('Hungary'),
            __('Iceland'),
            __('India'),
            __('Indonesia'),
            __('Iran, Islamic Republic Of'),
            __('Iraq'),
            __('Ireland'),
            __('Isle Of Man'),
            __('Israel'),
            __('Italy'),
            __('Jamaica'),
            __('Japan'),
            __('Jersey'),
            __('Jordan'),
            __('Kazakhstan'),
            __('Kenya'),
            __('Kiribati'),
            __('Korea'),
            __('Kuwait'),
            __('Kyrgyzstan'),
            __('Lao People\'s Democratic Republic'),
            __('Latvia'),
            __('Lebanon'),
            __('Lesotho'),
            __('Liberia'),
            __('Libyan Arab Jamahiriya'),
            __('Liechtenstein'),
            __('Lithuania'),
            __('Luxembourg'),
            __('Macao'),
            __('Macedonia'),
            __('Madagascar'),
            __('Malawi'),
            __('Malaysia'),
            __('Maldives'),
            __('Mali'),
            __('Malta'),
            __('Marshall Islands'),
            __('Martinique'),
            __('Mauritania'),
            __('Mauritius'),
            __('Mayotte'),
            __('Mexico'),
            __('Micronesia, Federated States Of'),
            __('Moldova'),
            __('Monaco'),
            __('Mongolia'),
            __('Montenegro'),
            __('Montserrat'),
            __('Morocco'),
            __('Mozambique'),
            __('Myanmar'),
            __('Namibia'),
            __('Nauru'),
            __('Nepal'),
            __('Netherlands'),
            __('Netherlands Antilles'),
            __('New Caledonia'),
            __('New Zealand'),
            __('Nicaragua'),
            __('Niger'),
            __('Nigeria'),
            __('Niue'),
            __('Norfolk Island'),
            __('Northern Mariana Islands'),
            __('Norway'),
            __('Oman'),
            __('Pakistan'),
            __('Palau'),
            __('Palestinian Territory, Occupied'),
            __('Panama'),
            __('Papua New Guinea'),
            __('Paraguay'),
            __('Peru'),
            __('Philippines'),
            __('Pitcairn'),
            __('Poland'),
            __('Portugal'),
            __('Puerto Rico'),
            __('Qatar'),
            __('Reunion'),
            __('Romania'),
            __('Russian Federation'),
            __('Rwanda'),
            __('Saint Barthelemy'),
            __('Saint Helena'),
            __('Saint Kitts And Nevis'),
            __('Saint Lucia'),
            __('Saint Martin'),
            __('Saint Pierre And Miquelon'),
            __('Saint Vincent And Grenadines'),
            __('Samoa'),
            __('San Marino'),
            __('Sao Tome And Principe'),
            __('Saudi Arabia'),
            __('Senegal'),
            __('Serbia'),
            __('Seychelles'),
            __('Sierra Leone'),
            __('Singapore'),
            __('Slovakia'),
            __('Slovenia'),
            __('Solomon Islands'),
            __('Somalia'),
            __('South Africa'),
            __('South Georgia And Sandwich Isl.'),
            __('Spain'),
            __('Sri Lanka'),
            __('Sudan'),
            __('Suriname'),
            __('Svalbard And Jan Mayen'),
            __('Swaziland'),
            __('Sweden'),
            __('Switzerland'),
            __('Syrian Arab Republic'),
            __('Taiwan'),
            __('Tajikistan'),
            __('Tanzania'),
            __('Thailand'),
            __('Timor-Leste'),
            __('Togo'),
            __('Tokelau'),
            __('Tonga'),
            __('Trinidad And Tobago'),
            __('Tunisia'),
            __('Turkey'),
            __('Turkmenistan'),
            __('Turks And Caicos Islands'),
            __('Tuvalu'),
            __('Uganda'),
            __('Ukraine'),
            __('United Arab Emirates'),
            __('United Kingdom'),
            __('United States'),
            __('United States Outlying Islands'),
            __('Uruguay'),
            __('Uzbekistan'),
            __('Vanuatu'),
            __('Venezuela'),
            __('Viet Nam'),
            __('Virgin Islands, British'),
            __('Virgin Islands, U.S.'),
            __('Wallis And Futuna'),
            __('Western Sahara'),
            __('Yemen'),
            __('Zambia'),
            __('Zimbabwe'),
        ]);
    }   

/*        $this->items([
            ['id'=>'AF', 'name'=> __('Afghanistan')],
            ['id'=>'AX', 'name'=> __('Aland Islands')],
            ['id'=>'AL', 'name'=> __('Albania')],
            ['id'=>'DZ', 'name'=> __('Algeria')],
            ['id'=>'AS', 'name'=> __('American Samoa')],
            ['id'=>'AD', 'name'=> __('Andorra')],
            ['id'=>'AO', 'name'=> __('Angola')],
            ['id'=>'AI', 'name'=> __('Anguilla')],
            ['id'=>'AQ', 'name'=> __('Antarctica')],
            ['id'=>'AG', 'name'=> __('Antigua And Barbuda')],
            ['id'=>'AR', 'name'=> __('Argentina')],
            ['id'=>'AM', 'name'=> __('Armenia')],
            ['id'=>'AW', 'name'=> __('Aruba')],
            ['id'=>'AU', 'name'=> __('Australia')],
            ['id'=>'AT', 'name'=> __('Austria')],
            ['id'=>'AZ', 'name'=> __('Azerbaijan')],
            ['id'=>'BS', 'name'=> __('Bahamas')],
            ['id'=>'BH', 'name'=> __('Bahrain')],
            ['id'=>'BD', 'name'=> __('Bangladesh')],
            ['id'=>'BB', 'name'=> __('Barbados')],
            ['id'=>'BY', 'name'=> __('Belarus')],
            ['id'=>'BE', 'name'=> __('Belgium')],
            ['id'=>'BZ', 'name'=> __('Belize')],
            ['id'=>'BJ', 'name'=> __('Benin')],
            ['id'=>'BM', 'name'=> __('Bermuda')],
            ['id'=>'BT', 'name'=> __('Bhutan')],
            ['id'=>'BO', 'name'=> __('Bolivia')],
            ['id'=>'BA', 'name'=> __('Bosnia And Herzegovina')],
            ['id'=>'BW', 'name'=> __('Botswana')],
            ['id'=>'BV', 'name'=> __('Bouvet Island')],
            ['id'=>'BR', 'name'=> __('Brazil')],
            ['id'=>'IO', 'name'=> __('British Indian Ocean Territory')],
            ['id'=>'BN', 'name'=> __('Brunei Darussalam')],
            ['id'=>'BG', 'name'=> __('Bulgaria')],
            ['id'=>'BF', 'name'=> __('Burkina Faso')],
            ['id'=>'BI', 'name'=> __('Burundi')],
            ['id'=>'KH', 'name'=> __('Cambodia')],
            ['id'=>'CM', 'name'=> __('Cameroon')],
            ['id'=>'CA', 'name'=> __('Canada')],
            ['id'=>'CV', 'name'=> __('Cape Verde')],
            ['id'=>'KY', 'name'=> __('Cayman Islands')],
            ['id'=>'CF', 'name'=> __('Central African Republic')],
            ['id'=>'TD', 'name'=> __('Chad')],
            ['id'=>'CL', 'name'=> __('Chile')],
            ['id'=>'CN', 'name'=> __('China')],
            ['id'=>'CX', 'name'=> __('Christmas Island')],
            ['id'=>'CC', 'name'=> __('Cocos (Keeling) Islands')],
            ['id'=>'CO', 'name'=> __('Colombia')],
            ['id'=>'KM', 'name'=> __('Comoros')],
            ['id'=>'CG', 'name'=> __('Congo')],
            ['id'=>'CD', 'name'=> __('Congo, Democratic Republic')],
            ['id'=>'CK', 'name'=> __('Cook Islands')],
            ['id'=>'CR', 'name'=> __('Costa Rica')],
            ['id'=>'CI', 'name'=> __('Cote D\'Ivoire')],
            ['id'=>'HR', 'name'=> __('Croatia')],
            ['id'=>'CU', 'name'=> __('Cuba')],
            ['id'=>'CY', 'name'=> __('Cyprus')],
            ['id'=>'CZ', 'name'=> __('Czech Republic')],
            ['id'=>'DK', 'name'=> __('Denmark')],
            ['id'=>'DJ', 'name'=> __('Djibouti')],
            ['id'=>'DM', 'name'=> __('Dominica')],
            ['id'=>'DO', 'name'=> __('Dominican Republic')],
            ['id'=>'EC', 'name'=> __('Ecuador')],
            ['id'=>'EG', 'name'=> __('Egypt')],
            ['id'=>'SV', 'name'=> __('El Salvador')],
            ['id'=>'GQ', 'name'=> __('Equatorial Guinea')],
            ['id'=>'ER', 'name'=> __('Eritrea')],
            ['id'=>'EE', 'name'=> __('Estonia')],
            ['id'=>'ET', 'name'=> __('Ethiopia')],
            ['id'=>'FK', 'name'=> __('Falkland Islands (Malvinas)')],
            ['id'=>'FO', 'name'=> __('Faroe Islands')],
            ['id'=>'FJ', 'name'=> __('Fiji')],
            ['id'=>'FI', 'name'=> __('Finland')],
            ['id'=>'FR', 'name'=> __('France')],
            ['id'=>'GF', 'name'=> __('French Guiana')],
            ['id'=>'PF', 'name'=> __('French Polynesia')],
            ['id'=>'TF', 'name'=> __('French Southern Territories')],
            ['id'=>'GA', 'name'=> __('Gabon')],
            ['id'=>'GM', 'name'=> __('Gambia')],
            ['id'=>'GE', 'name'=> __('Georgia')],
            ['id'=>'DE', 'name'=> __('Germany')],
            ['id'=>'GH', 'name'=> __('Ghana')],
            ['id'=>'GI', 'name'=> __('Gibraltar')],
            ['id'=>'GR', 'name'=> __('Greece')],
            ['id'=>'GL', 'name'=> __('Greenland')],
            ['id'=>'GD', 'name'=> __('Grenada')],
            ['id'=>'GP', 'name'=> __('Guadeloupe')],
            ['id'=>'GU', 'name'=> __('Guam')],
            ['id'=>'GT', 'name'=> __('Guatemala')],
            ['id'=>'GG', 'name'=> __('Guernsey')],
            ['id'=>'GN', 'name'=> __('Guinea')],
            ['id'=>'GW', 'name'=> __('Guinea-Bissau')],
            ['id'=>'GY', 'name'=> __('Guyana')],
            ['id'=>'HT', 'name'=> __('Haiti')],
            ['id'=>'HM', 'name'=> __('Heard Island & Mcdonald Islands')],
            ['id'=>'VA', 'name'=> __('Holy See (Vatican City State)')],
            ['id'=>'HN', 'name'=> __('Honduras')],
            ['id'=>'HK', 'name'=> __('Hong Kong')],
            ['id'=>'HU', 'name'=> __('Hungary')],
            ['id'=>'IS', 'name'=> __('Iceland')],
            ['id'=>'IN', 'name'=> __('India')],
            ['id'=>'ID', 'name'=> __('Indonesia')],
            ['id'=>'IR', 'name'=> __('Iran, Islamic Republic Of')],
            ['id'=>'IQ', 'name'=> __('Iraq')],
            ['id'=>'IE', 'name'=> __('Ireland')],
            ['id'=>'IM', 'name'=> __('Isle Of Man')],
            ['id'=>'IL', 'name'=> __('Israel')],
            ['id'=>'IT', 'name'=> __('Italy')],
            ['id'=>'JM', 'name'=> __('Jamaica')],
            ['id'=>'JP', 'name'=> __('Japan')],
            ['id'=>'JE', 'name'=> __('Jersey')],
            ['id'=>'JO', 'name'=> __('Jordan')],
            ['id'=>'KZ', 'name'=> __('Kazakhstan')],
            ['id'=>'KE', 'name'=> __('Kenya')],
            ['id'=>'KI', 'name'=> __('Kiribati')],
            ['id'=>'KR', 'name'=> __('Korea')],
            ['id'=>'KW', 'name'=> __('Kuwait')],
            ['id'=>'KG', 'name'=> __('Kyrgyzstan')],
            ['id'=>'LA', 'name'=> __('Lao People\'s Democratic Republic')],
            ['id'=>'LV', 'name'=> __('Latvia')],
            ['id'=>'LB', 'name'=> __('Lebanon')],
            ['id'=>'LS', 'name'=> __('Lesotho')],
            ['id'=>'LR', 'name'=> __('Liberia')],
            ['id'=>'LY', 'name'=> __('Libyan Arab Jamahiriya')],
            ['id'=>'LI', 'name'=> __('Liechtenstein')],
            ['id'=>'LT', 'name'=> __('Lithuania')],
            ['id'=>'LU', 'name'=> __('Luxembourg')],
            ['id'=>'MO', 'name'=> __('Macao')],
            ['id'=>'MK', 'name'=> __('Macedonia')],
            ['id'=>'MG', 'name'=> __('Madagascar')],
            ['id'=>'MW', 'name'=> __('Malawi')],
            ['id'=>'MY', 'name'=> __('Malaysia')],
            ['id'=>'MV', 'name'=> __('Maldives')],
            ['id'=>'ML', 'name'=> __('Mali')],
            ['id'=>'MT', 'name'=> __('Malta')],
            ['id'=>'MH', 'name'=> __('Marshall Islands')],
            ['id'=>'MQ', 'name'=> __('Martinique')],
            ['id'=>'MR', 'name'=> __('Mauritania')],
            ['id'=>'MU', 'name'=> __('Mauritius')],
            ['id'=>'YT', 'name'=> __('Mayotte')],
            ['id'=>'MX', 'name'=> __('Mexico')],
            ['id'=>'FM', 'name'=> __('Micronesia, Federated States Of')],
            ['id'=>'MD', 'name'=> __('Moldova')],
            ['id'=>'MC', 'name'=> __('Monaco')],
            ['id'=>'MN', 'name'=> __('Mongolia')],
            ['id'=>'ME', 'name'=> __('Montenegro')],
            ['id'=>'MS', 'name'=> __('Montserrat')],
            ['id'=>'MA', 'name'=> __('Morocco')],
            ['id'=>'MZ', 'name'=> __('Mozambique')],
            ['id'=>'MM', 'name'=> __('Myanmar')],
            ['id'=>'NA', 'name'=> __('Namibia')],
            ['id'=>'NR', 'name'=> __('Nauru')],
            ['id'=>'NP', 'name'=> __('Nepal')],
            ['id'=>'NL', 'name'=> __('Netherlands')],
            ['id'=>'AN', 'name'=> __('Netherlands Antilles')],
            ['id'=>'NC', 'name'=> __('New Caledonia')],
            ['id'=>'NZ', 'name'=> __('New Zealand')],
            ['id'=>'NI', 'name'=> __('Nicaragua')],
            ['id'=>'NE', 'name'=> __('Niger')],
            ['id'=>'NG', 'name'=> __('Nigeria')],
            ['id'=>'NU', 'name'=> __('Niue')],
            ['id'=>'NF', 'name'=> __('Norfolk Island')],
            ['id'=>'MP', 'name'=> __('Northern Mariana Islands')],
            ['id'=>'NO', 'name'=> __('Norway')],
            ['id'=>'OM', 'name'=> __('Oman')],
            ['id'=>'PK', 'name'=> __('Pakistan')],
            ['id'=>'PW', 'name'=> __('Palau')],
            ['id'=>'PS', 'name'=> __('Palestinian Territory, Occupied')],
            ['id'=>'PA', 'name'=> __('Panama')],
            ['id'=>'PG', 'name'=> __('Papua New Guinea')],
            ['id'=>'PY', 'name'=> __('Paraguay')],
            ['id'=>'PE', 'name'=> __('Peru')],
            ['id'=>'PH', 'name'=> __('Philippines')],
            ['id'=>'PN', 'name'=> __('Pitcairn')],
            ['id'=>'PL', 'name'=> __('Poland')],
            ['id'=>'PT', 'name'=> __('Portugal')],
            ['id'=>'PR', 'name'=> __('Puerto Rico')],
            ['id'=>'QA', 'name'=> __('Qatar')],
            ['id'=>'RE', 'name'=> __('Reunion')],
            ['id'=>'RO', 'name'=> __('Romania')],
            ['id'=>'RU', 'name'=> __('Russian Federation')],
            ['id'=>'RW', 'name'=> __('Rwanda')],
            ['id'=>'BL', 'name'=> __('Saint Barthelemy')],
            ['id'=>'SH', 'name'=> __('Saint Helena')],
            ['id'=>'KN', 'name'=> __('Saint Kitts And Nevis')],
            ['id'=>'LC', 'name'=> __('Saint Lucia')],
            ['id'=>'MF', 'name'=> __('Saint Martin')],
            ['id'=>'PM', 'name'=> __('Saint Pierre And Miquelon')],
            ['id'=>'VC', 'name'=> __('Saint Vincent And Grenadines')],
            ['id'=>'WS', 'name'=> __('Samoa')],
            ['id'=>'SM', 'name'=> __('San Marino')],
            ['id'=>'ST', 'name'=> __('Sao Tome And Principe')],
            ['id'=>'SA', 'name'=> __('Saudi Arabia')],
            ['id'=>'SN', 'name'=> __('Senegal')],
            ['id'=>'RS', 'name'=> __('Serbia')],
            ['id'=>'SC', 'name'=> __('Seychelles')],
            ['id'=>'SL', 'name'=> __('Sierra Leone')],
            ['id'=>'SG', 'name'=> __('Singapore')],
            ['id'=>'SK', 'name'=> __('Slovakia')],
            ['id'=>'SI', 'name'=> __('Slovenia')],
            ['id'=>'SB', 'name'=> __('Solomon Islands')],
            ['id'=>'SO', 'name'=> __('Somalia')],
            ['id'=>'ZA', 'name'=> __('South Africa')],
            ['id'=>'GS', 'name'=> __('South Georgia And Sandwich Isl.')],
            ['id'=>'ES', 'name'=> __('Spain')],
            ['id'=>'LK', 'name'=> __('Sri Lanka')],
            ['id'=>'SD', 'name'=> __('Sudan')],
            ['id'=>'SR', 'name'=> __('Suriname')],
            ['id'=>'SJ', 'name'=> __('Svalbard And Jan Mayen')],
            ['id'=>'SZ', 'name'=> __('Swaziland')],
            ['id'=>'SE', 'name'=> __('Sweden')],
            ['id'=>'CH', 'name'=> __('Switzerland')],
            ['id'=>'SY', 'name'=> __('Syrian Arab Republic')],
            ['id'=>'TW', 'name'=> __('Taiwan')],
            ['id'=>'TJ', 'name'=> __('Tajikistan')],
            ['id'=>'TZ', 'name'=> __('Tanzania')],
            ['id'=>'TH', 'name'=> __('Thailand')],
            ['id'=>'TL', 'name'=> __('Timor-Leste')],
            ['id'=>'TG', 'name'=> __('Togo')],
            ['id'=>'TK', 'name'=> __('Tokelau')],
            ['id'=>'TO', 'name'=> __('Tonga')],
            ['id'=>'TT', 'name'=> __('Trinidad And Tobago')],
            ['id'=>'TN', 'name'=> __('Tunisia')],
            ['id'=>'TR', 'name'=> __('Turkey')],
            ['id'=>'TM', 'name'=> __('Turkmenistan')],
            ['id'=>'TC', 'name'=> __('Turks And Caicos Islands')],
            ['id'=>'TV', 'name'=> __('Tuvalu')],
            ['id'=>'UG', 'name'=> __('Uganda')],
            ['id'=>'UA', 'name'=> __('Ukraine')],
            ['id'=>'AE', 'name'=> __('United Arab Emirates')],
            ['id'=>'GB', 'name'=> __('United Kingdom')],
            ['id'=>'US', 'name'=> __('United States')],
            ['id'=>'UM', 'name'=> __('United States Outlying Islands')],
            ['id'=>'UY', 'name'=> __('Uruguay')],
            ['id'=>'UZ', 'name'=> __('Uzbekistan')],
            ['id'=>'VU', 'name'=> __('Vanuatu')],
            ['id'=>'VE', 'name'=> __('Venezuela')],
            ['id'=>'VN', 'name'=> __('Viet Nam')],
            ['id'=>'VG', 'name'=> __('Virgin Islands, British')],
            ['id'=>'VI', 'name'=> __('Virgin Islands, U.S.')],
            ['id'=>'WF', 'name'=> __('Wallis And Futuna')],
            ['id'=>'EH', 'name'=> __('Western Sahara')],
            ['id'=>'YE', 'name'=> __('Yemen')],
            ['id'=>'ZM', 'name'=> __('Zambia')],
            ['id'=>'ZW', 'name'=> __('Zimbabwe')]
        ]);
*/
}